"use client";

import { useEffect, useRef, useState } from "react";
import { addZip, dataUrl, GeneratedSong, GeneratedTrack, generateSong, genres, SwingLevel } from "../lib/generator";

const stages=["Picking a tempo that can swim...","Teaching the bassline to float...","Sprinkling hooks into the chorus...","Making the drums less awkward...","Packing your MIDI suitcase..."];

export default function Home(){const [genre,setGenre]=useState(genres[0].id);const [seed,setSeed]=useState("");const [trackCount,setTrackCount]=useState("");const [bpm,setBpm]=useState("");const [swingLevel,setSwingLevel]=useState<SwingLevel|"">("");const [density,setDensity]=useState("0.8");const [loading,setLoading]=useState(false);const [stage,setStage]=useState(0);const [song,setSong]=useState<GeneratedSong|null>(null);const [error,setError]=useState("");const audio=useRef<AudioContext|null>(null);const timers=useRef<number[]>([]);const profile=genres.find(g=>g.id===genre)!;
useEffect(()=>{if(!loading)return;setStage(0);const id=window.setInterval(()=>setStage(s=>Math.min(stages.length-1,s+1)),520);return()=>clearInterval(id)},[loading]);
async function jump(){setError("");setLoading(true);stop();await new Promise(r=>setTimeout(r,760));try{const made=generateSong({genreId:genre,seed,advancedOptions:{trackCount:trackCount?Number(trackCount):undefined,bpm:bpm?Number(bpm):undefined,swingLevel:swingLevel||undefined,density:Number(density)}});setStage(4);setSong(await addZip(made))}catch(e){setError(e instanceof Error?e.message:"The song slipped on the pool tiles. Try generating again.")}finally{setLoading(false)}}
function stop(){timers.current.forEach(clearTimeout);timers.current=[];audio.current?.close();audio.current=null}
function play(track?:GeneratedTrack){stop();const ctx=new AudioContext();audio.current=ctx;const tracks=track?[track]:song?.tracks??[];tracks.forEach(t=>t.events.slice(0,900).forEach(e=>{const o=ctx.createOscillator();const g=ctx.createGain();const drum=t.drum;const secondsPerBeat=60/(song?.bpm||120);const startAt=ctx.currentTime+e.time*secondsPerBeat;const freq=drum?90+e.note:440*Math.pow(2,(e.note-69)/12);o.type=drum?"triangle":t.role==="bass"?"sawtooth":"sine";o.frequency.value=freq;g.gain.setValueAtTime(0,startAt);g.gain.linearRampToValueAtTime(e.velocity*(drum?.06:.045),startAt+.01);g.gain.exponentialRampToValueAtTime(.0001,startAt+e.duration*secondsPerBeat);o.connect(g).connect(ctx.destination);const a=window.setTimeout(()=>{o.start();o.stop(ctx.currentTime+e.duration*secondsPerBeat+.05)},e.time*secondsPerBeat*1000);timers.current.push(a)}))}
return <main className="page"><section className="hero"><div><h1 className="brand">JIWW</h1><p className="subtitle">Jump In, Water&apos;s Wet</p><p className="copy">Pick a genre and get a complete MIDI song sketch with drums, bass, chords, hooks, sections, stems, and a ZIP. Don&apos;t overthink it. The pool is already making music.</p></div><div className="pool-card"><h2>Make a Splash</h2><div className="controls"><div className="row"><label className="field">Seed<input value={seed} onChange={e=>setSeed(e.target.value)} placeholder="optional-user-seed" /></label><label className="field">Tracks<input type="number" min="4" max="16" value={trackCount} onChange={e=>setTrackCount(e.target.value)} placeholder={`${profile.trackCountRange[0]}-${profile.trackCountRange[1]}`} /></label></div><div className="row"><label className="field">BPM<input type="number" value={bpm} onChange={e=>setBpm(e.target.value)} placeholder={`${profile.bpmRange[0]}-${profile.bpmRange[1]}`} /></label><label className="field">Swing<select value={swingLevel} onChange={e=>setSwingLevel(e.target.value as SwingLevel|"")}><option value="">Genre decides</option><option>straight</option><option>light</option><option>medium</option><option>heavy</option></select></label></div><label className="field">Density<input type="range" min="0.4" max="1" step="0.05" value={density} onChange={e=>setDensity(e.target.value)} /></label><button className="cta" onClick={jump}>Jump In</button></div></div></section><section className="genres" aria-label="Genre selector">{genres.map(g=><button key={g.id} className={`genre ${genre===g.id?"selected":""}`} onClick={()=>setGenre(g.id)} aria-pressed={genre===g.id}><strong>{g.icon} {g.displayName}</strong><span>{g.bpmRange[0]}-{g.bpmRange[1]} BPM</span><span>{g.groove}</span></button>)}</section>{error&&<div className="error">{error}</div>}{song&&<Results song={song} play={play} stop={stop} regenerate={jump}/>} {loading&&<div className="modal" role="dialog" aria-modal="true" aria-label="Generating song"><div className="pool-card loader"><div className="ripple"/><h2>The water&apos;s getting musical...</h2><p>{stages[stage]}</p><div className="bar"><div style={{width:`${(stage+1)/stages.length*100}%`}} /></div><p>Hold tight. Your MIDI suitcase is being packed in memory.</p><button className="small alt" onClick={()=>setLoading(false)}>Cancel</button></div></div>}</main>}
function Results({song,play,stop,regenerate}:{song:GeneratedSong;play:(t?:GeneratedTrack)=>void;stop:()=>void;regenerate:()=>void}){const total=song.tracks.reduce((n,t)=>n+t.noteCount,0);return <section className="results"><div className="pool-card"><h2>Your song just cannonballed into existence.</h2><h3>{song.title}</h3><div className="meta"><span className="pill">Genre: {song.genreName}</span><span className="pill">BPM: {song.bpm}</span><span className="pill">Key: {song.key}</span><span className="pill">Swing: {song.swingLevel}, {song.swingAmount}%</span><span className="pill">Tracks: {song.tracks.length}</span><span className="pill">Length: {song.lengthBars} bars</span></div><div className="actions" style={{marginTop:16}}><button className="small" onClick={()=>play()}>Play Full Song</button><button className="small alt" onClick={stop}>Stop</button><a className="small" href={dataUrl(song.fullMidiBase64,"audio/midi")} download={`JIWW_${song.genreName}_${song.seed}_FullArrangement.mid`}>Download full MIDI</a><a className="small alt" href={dataUrl(song.zipBase64,"application/zip")} download={song.zipFileName}>Download the Whole Pool</a><button className="small" onClick={regenerate}>Generate Another Splash</button></div><p>{total.toLocaleString()} notes across stems, with a denser final chorus and verse/chorus participation logic.</p></div><div className="pool-card"><h3>Arrangement</h3><div className="arrangement">{song.arrangement.map(s=><div className="section" key={s.name}><strong>{s.name}</strong><br/><span>Bar {s.startBar}</span><br/><span>{s.bars} bars</span><br/><span>Energy {Math.round(s.energy*100)}%</span></div>)}</div></div><div className="pool-card"><h3>Tracks</h3><div className="tracks">{song.tracks.map(t=><article className="track" key={t.id}><div><strong>{t.id.replace("_"," ")} - {t.name}</strong><p>Role: {t.role} | Instrument: {t.drum?"General MIDI Drum Kit":`GM Program ${t.program}`} | Channel: {t.channel+1} | Notes: {t.noteCount}</p><p>Active: {Object.entries(t.sectionParticipation).filter(([,v])=>v).map(([k])=>k).join(", ")}</p></div><div className="actions"><button className="small" onClick={()=>play(t)}>Play solo</button><button className="small alt" onClick={stop}>Stop</button><a className="small" href={dataUrl(t.midiBase64,"audio/midi")} download={t.fileName}>Grab this track</a></div></article>)}</div></div></section>}
