import { Midi } from "@tonejs/midi";
import JSZip from "jszip";

export type TrackRole="drums"|"percussion"|"bass"|"chords"|"melody"|"hook"|"countermelody"|"pad"|"arp"|"lead"|"texture"|"fx";
export type SwingLevel="straight"|"light"|"medium"|"heavy";
export type MidiEvent={time:number;duration:number;note:number;velocity:number};
export type TrackDef={name:string;role:TrackRole;program:number|null;drum:boolean;channel:number};
export type GenreProfile={id:string;displayName:string;bpmRange:[number,number];swingRange:[number,number];trackCountRange:[number,number];density:[number,number];keys:string[];scales:string[];groove:string;icon:string;tracks:TrackDef[];progressions:number[][]};
export type ArrangementSection={name:string;startBar:number;bars:number;energy:number};
export type GeneratedTrack=TrackDef&{id:string;sectionParticipation:Record<string,boolean>;events:MidiEvent[];midiBase64:string;fileName:string;noteCount:number};
export type GeneratedSong={songId:string;seed:string;title:string;genreId:string;genreName:string;bpm:number;swingAmount:number;swingLevel:SwingLevel;key:string;scale:string;timeSignature:[number,number];lengthBars:number;arrangement:ArrangementSection[];tracks:GeneratedTrack[];fullMidiBase64:string;zipBase64:string;zipFileName:string};
type Request={genreId:string;seed?:string;advancedOptions?:{trackCount?:number;bpm?:number;swingLevel?:SwingLevel;songLengthBars?:number;density?:number}};

const GM={piano:0,ep:4,organ:16,guitar:27,muted:28,bass:33,slap:36,strings:48,brass:61,sax:65,lead:80,square:81,pad:88,fx:97,pluck:45,clav:7};
const baseTracks=(names:[string,TrackRole,number|null,boolean][]):TrackDef[]=>names.map((n,i)=>({name:n[0],role:n[1],program:n[2],drum:n[3],channel:n[3]?9:(i%8)}));
type TrackSeed=[string,TrackRole,number|null,boolean];
export const genres:GenreProfile[]=[
  g("house","House",[118,128],[0,18],[8,14],"Four-on-the-floor pool party","🏠",[["Splashy Drum Kit","drums",null,true],["Cabana Percussion","percussion",null,true],["Rubber Bass","bass",GM.bass,false],["Piano Chords","chords",GM.piano,false],["Organ Stabs","chords",GM.organ,false],["Bubble Pluck","hook",GM.pluck,false],["Warm Pad","pad",GM.pad,false],["Lead Hook","lead",GM.lead,false],["Foam Riser","fx",GM.fx,false]]),
  g("techno","Techno",[124,140],[0,14],[8,15],"Chrome kick in a deep pool","⚙",[["Machine Drums","drums",null,true],["Ticking Hats","percussion",null,true],["Sub Pulse","bass",GM.bass,false],["Dark Stab","chords",GM.organ,false],["Acid Thread","arp",GM.lead,false],["Pressure Pad","pad",GM.pad,false],["Signal Lead","lead",GM.square,false],["Valve FX","fx",GM.fx,false]]),
  g("drumAndBass","Drum & Bass",[160,176],[0,12],[8,16],"Breakbeats diving headfirst","↯",[["Breakbeat Kit","drums",null,true],["Ghost Hats","percussion",null,true],["Sub Bass","bass",GM.bass,false],["Reese Bass","bass",GM.lead,false],["Stab Chords","chords",GM.ep,false],["Fast Arp","arp",GM.square,false],["Atmosphere Pad","pad",GM.pad,false],["Neon Hook","hook",GM.lead,false],["Impact FX","fx",GM.fx,false]]),
  g("ukGarage","UK Garage",[128,138],[16,30],[8,14],"Shuffled steps on wet tiles","☔",[["Skippy Drums","drums",null,true],["Rim Percussion","percussion",null,true],["Bouncy Sub","bass",GM.bass,false],["Rhodes Chops","chords",GM.ep,false],["Vocal-ish Lead","hook",GM.lead,false],["Glass Counter","countermelody",GM.pluck,false],["Soft Pad","pad",GM.pad,false],["Splash FX","fx",GM.fx,false]]),
  g("hipHop","Hip-Hop",[80,100],[12,32],[6,12],"Head-nod float session","🎧",[["Dusty Drum Kit","drums",null,true],["Lazy Percussion","percussion",null,true],["Round Bass","bass",GM.bass,false],["Sample Piano","chords",GM.piano,false],["Muted Guitar","melody",GM.muted,false],["Main Hook","hook",GM.lead,false],["String Bed","pad",GM.strings,false]]),
  g("trap","Trap",[130,150],[4,18],[7,13],"Half-time splash with hat rain","💧",[["Trap Kit","drums",null,true],["Hat Sprinkler","percussion",null,true],["808 Bass","bass",GM.bass,false],["Minor Bells","hook",GM.pluck,false],["Dark Pad","pad",GM.pad,false],["Lead Siren","lead",GM.lead,false],["Snare FX","fx",GM.fx,false]]),
  g("lofiHipHop","Lo-Fi Hip-Hop",[68,92],[24,45],[6,12],"Wobbly towel-on-the-speaker groove","☕",[["Dusty Drums","drums",null,true],["Vinyl Ticks","texture",GM.fx,false],["Soft Bass","bass",GM.bass,false],["Misty Rhodes","chords",GM.ep,false],["Sleepy Guitar","melody",GM.guitar,false],["Bell Hook","hook",GM.pluck,false],["Blanket Pad","pad",GM.pad,false]]),
  g("synthwave","Synthwave",[84,112],[0,12],[8,14],"Sunset pool neon cruise","🌆",[["Electronic Drums","drums",null,true],["Gated Snaps","percussion",null,true],["Pulse Synth Bass","bass",GM.bass,false],["Synth Strings","chords",GM.strings,false],["Warm Pad","pad",GM.pad,false],["Arpeggiated Synth","arp",GM.square,false],["Saw Lead Hook","hook",GM.lead,false],["Laser FX","fx",GM.fx,false]]),
  g("ambient","Ambient",[60,90],[0,20],[4,10],"Slow ripples in a moon pool","🌙",[["Soft Pulse","drums",null,true],["Deep Drone","bass",GM.bass,false],["Cloud Pad","pad",GM.pad,false],["Piano Drops","melody",GM.piano,false],["String Mist","chords",GM.strings,false],["Distant Bell","hook",GM.pluck,false],["Water Texture","texture",GM.fx,false]]),
  g("funk","Funk",[90,115],[18,32],[8,14],"Syncopated cannonball grin","🕺",[["Pocket Drums","drums",null,true],["Shaker Crew","percussion",null,true],["Slap Bass","bass",GM.slap,false],["Clavinet Bubbles","chords",GM.clav,false],["Clean Guitar Chops","chords",GM.guitar,false],["Brass Splashes","hook",GM.brass,false],["Organ Grease","pad",GM.organ,false]]),
  g("disco","Disco",[110,125],[6,20],[9,15],"Mirrorball by the lazy river","✨",[["Disco Kit","drums",null,true],["Tambourine","percussion",null,true],["Octave Bass","bass",GM.bass,false],["Piano Glitter","chords",GM.piano,false],["String Ensemble","pad",GM.strings,false],["Brass Hook","hook",GM.brass,false],["Guitar Chucks","chords",GM.guitar,false],["Party FX","fx",GM.fx,false]]),
  g("pop","Pop",[95,125],[0,18],[7,13],"Big chorus inflatable raft","🎤",[["Pop Drum Kit","drums",null,true],["Clap Stack","percussion",null,true],["Synth Bass","bass",GM.bass,false],["Piano Chords","chords",GM.piano,false],["Clean Guitar","melody",GM.guitar,false],["String Lift","pad",GM.strings,false],["Topline Hook","hook",GM.lead,false]]),
  g("indieRock","Indie Rock",[95,145],[0,16],[6,12],"Garage band at the swim club","🎸",[["Indie Drums","drums",null,true],["Picked Bass","bass",GM.bass,false],["Jangle Guitar","chords",GM.guitar,false],["Fuzz Lead","lead",GM.lead,false],["Organ Pad","pad",GM.organ,false],["Singable Hook","hook",GM.square,false]]),
  g("reggaeton","Reggaeton",[85,105],[4,18],[7,13],"Dembow in the sun lane","🌴",[["Dembow Kit","drums",null,true],["Hand Percussion","percussion",null,true],["Sub Bass","bass",GM.bass,false],["Muted Guitar","chords",GM.muted,false],["Pluck Hook","hook",GM.pluck,false],["Airy Pad","pad",GM.pad,false],["Club FX","fx",GM.fx,false]]),
  g("afrobeat","Afrobeat",[95,120],[12,28],[9,16],"Interlocking waves and sunshine","🥁",[["Afrobeat Drums","drums",null,true],["Talking Percussion","percussion",null,true],["Rolling Bass","bass",GM.bass,false],["Highlife Guitar","chords",GM.guitar,false],["Organ Comp","chords",GM.organ,false],["Horn Hook","hook",GM.brass,false],["Marimba Counter","countermelody",GM.pluck,false]]),
  g("jazzFusion","Jazz Fusion",[90,140],[18,40],[8,14],"Odd sunglasses in the deep end","🎷",[["Ride Drums","drums",null,true],["Aux Percussion","percussion",null,true],["Fingered Bass","bass",GM.bass,false],["Electric Piano","chords",GM.ep,false],["Jazz Guitar","chords",GM.guitar,false],["Sax Hook","hook",GM.sax,false],["Organ Lead","lead",GM.organ,false],["String Pad","pad",GM.strings,false]])
];
function g(id:string,displayName:string,bpmRange:[number,number],swingRange:[number,number],trackCountRange:[number,number],groove:string,icon:string,tracks:TrackSeed[]):GenreProfile{return{id,displayName,bpmRange,swingRange,trackCountRange,density:[.55,.95],keys:["C","D","E","F","G","A","Bb"],scales:["major","natural_minor","dorian","mixolydian"],groove,icon,tracks:baseTracks(tracks),progressions:[[0,5,3,4],[0,3,4,4],[5,3,0,4],[0,4,5,3]]}};
const levels:Record<SwingLevel,[number,number]>={straight:[0,5],light:[6,15],medium:[16,30],heavy:[31,50]};
const titles=["Tiny Poolside Victory","Cannonball Moonlight","Floatie Full Of Hooks","Wet Sneakers Anthem","Chorus In The Kiddie Pool","Deep End Daydream"];
const scales:Record<string,number[]>={major:[0,2,4,5,7,9,11],natural_minor:[0,2,3,5,7,8,10],dorian:[0,2,3,5,7,9,10],mixolydian:[0,2,4,5,7,9,10]};
const roots:Record<string,number>={C:0,D:2,E:4,F:5,G:7,A:9,Bb:10};

export function generateSong(req:Request):GeneratedSong{const profile=genres.find(x=>x.id===req.genreId);if(!profile)throw new Error("unsupported genre");const seed=req.seed?.trim()||Math.random().toString(36).slice(2,8);const rnd=mulberry(hash(seed+profile.id));const bpm=req.advancedOptions?.bpm??ri(rnd,...profile.bpmRange);if(bpm<profile.bpmRange[0]||bpm>profile.bpmRange[1])throw new Error("That BPM wandered outside the pool fence. Pick one inside the genre range.");const count=clamp(req.advancedOptions?.trackCount??ri(rnd,...profile.trackCountRange),4,16);const level=req.advancedOptions?.swingLevel??swingLevelFor(profile.swingRange,rnd);const swingAmount=clamp(ri(rnd,Math.max(profile.swingRange[0],levels[level][0]),Math.min(profile.swingRange[1],levels[level][1])),profile.swingRange[0],profile.swingRange[1]);const key=pick(rnd,profile.keys);const scale=pick(rnd,profile.scales);const arrangement=makeArrangement(profile,req.advancedOptions?.songLengthBars);const lengthBars=arrangement.at(-1)!.startBar+arrangement.at(-1)!.bars-1;const selected=chooseTracks(profile,count);const prog=pick(rnd,profile.progressions);const tracks=selected.map((def,i)=>makeTrack(def,i,profile,arrangement,prog,key,scale,rnd,swingAmount));const songId="song_"+hash(seed+profile.id).toString(36);const shell={songId,seed,title:pick(rnd,titles),genreId:profile.id,genreName:profile.displayName,bpm,swingAmount,swingLevel:level,key:key+" "+scale.replace("natural_","").replace("_"," "),scale,timeSignature:[4,4] as [number,number],lengthBars,arrangement,tracks,fullMidiBase64:"",zipBase64:"",zipFileName:`JIWW_${profile.displayName.replace(/\s/g,"")}_${seed}_MIDI_Stems.zip`};const full=renderMidi(shell,tracks);tracks.forEach(t=>{t.midiBase64=bytesToBase64(renderMidi(shell,[t]));t.fileName=`JIWW_${profile.displayName.replace(/\s/g,"")}_${seed}_${t.id.slice(-2)}_${safe(t.name)}.mid`});shell.fullMidiBase64=bytesToBase64(full);return shell}
export async function addZip(song:GeneratedSong){const zip=new JSZip();zip.file("song-info.json",JSON.stringify({...song,zipBase64:"",tracks:song.tracks.map(t=>({...t,midiBase64:""}))},null,2));zip.file("full-arrangement.mid",base64ToBytes(song.fullMidiBase64));const folder=zip.folder("tracks")!;song.tracks.forEach(t=>folder.file(`${t.id.slice(-2)}-${safe(t.role)}.mid`,base64ToBytes(t.midiBase64)));song.zipBase64=await zip.generateAsync({type:"base64"});return song}
function makeArrangement(profile:GenreProfile,want?:number):ArrangementSection[]{const compact=profile.id.includes("hip")||profile.id==="pop"||profile.id==="funk";const bars=compact?[4,12,12,12,12,8,16,4]:[8,16,16,16,16,8,16,8];let s=1;const arr=["Intro","Verse A","Chorus A","Verse B","Chorus B",profile.id==="drumAndBass"||profile.id==="techno"?"Breakdown":"Bridge","Final Chorus","Outro"].map((name,i)=>{const sec={name,startBar:s,bars:bars[i],energy:[.35,.55,.85,.6,.9,.45,1,.3][i]};s+=bars[i];return sec});if(want&&want>=64&&want<=128){const diff=want-(s-1);arr[6].bars+=diff;s=1;arr.forEach(a=>{a.startBar=s;s+=a.bars})}return arr}
function chooseTracks(p:GenreProfile,c:number){const req=["drums","bass","chords","hook"];const out:TrackDef[]=[];req.forEach(r=>{const t=p.tracks.find(x=>x.role===r||r==="chords"&&["chords","pad"].includes(x.role));if(t&&!out.includes(t))out.push(t)});p.tracks.forEach(t=>{if(out.length<c&&!out.includes(t))out.push(t)});return out.slice(0,c)}
function makeTrack(def:TrackDef,i:number,p:GenreProfile,arr:ArrangementSection[],prog:number[],key:string,scale:string,rnd:()=>number,swing:number):GeneratedTrack{const participation:Object=Object.fromEntries(arr.map(s=>[s.name,active(def.role,s.energy,s.name)]));const events:MidiEvent[]=[];arr.forEach(sec=>{if(!(participation as Record<string,boolean>)[sec.name])return;for(let b=0;b<sec.bars;b++){const bar=sec.startBar-1+b;const degree=prog[bar%prog.length];events.push(...pattern(def,bar,degree,key,scale,sec,rnd,swing,p.id))}});return{...def,id:`track_${String(i+1).padStart(2,"0")}`,sectionParticipation:participation as Record<string,boolean>,events,midiBase64:"",fileName:"",noteCount:events.length}}
function pattern(def:TrackDef,bar:number,degree:number,key:string,scale:string,sec:ArrangementSection,rnd:()=>number,swing:number,genre:string){const ev:MidiEvent[]=[];const root=48+roots[key]+scales[scale][degree%7];const add=(beat:number,dur:number,note:number,vel=.75)=>ev.push({time:bar*4+swingBeat(beat,swing)+human(rnd,.018),duration:dur,note,velocity:clamp(vel+human(rnd,.08),.2,1)});if(def.drum){const dnb=genre==="drumAndBass";const reg=genre==="reggaeton";[0,reg?1.5:2].forEach(x=>add(x,.08,36,.9));if(sec.energy>.8)add(3,.08,36,.82);[dnb?1:1,3].forEach(x=>add(x,.08,38,.85));for(let x=0;x<4;x+=.5)add(x,.05,sec.energy>.75?42:44,.45+sec.energy*.25);if(sec.name.includes("Chorus")&&bar%4===3)[3.25,3.5,3.75].forEach(x=>add(x,.05,45,.7));return ev}if(def.role==="bass"){[0,genre==="funk"?.75:1.5,2.5,3.5].forEach((x,j)=>add(x,.35,root-12+(j%3===2?12:0),.65+sec.energy*.25));return ev}if(["chords","pad"].includes(def.role)){const notes=[root,root+scales[scale][2],root+scales[scale][4]].map(n=>n+12);const beats=def.role==="pad"?[0]:[0,2];beats.forEach(x=>notes.forEach(n=>add(x,def.role==="pad"?3.7:1.4,n,.46+sec.energy*.22)));return ev}if(def.role==="arp"){for(let x=0;x<4;x+=.5)add(x,.25,root+12+scales[scale][Math.floor((x*2)%7)],.55+sec.energy*.2);return ev}if(["hook","lead","melody","countermelody"].includes(def.role)){const motif=[0,2,4,5,4,2,1,0];for(let x=0;x<4;x+=.5){if(!sec.name.includes("Chorus")&&x>1.5&&def.role==="hook")continue;if(rnd()<.16)continue;const idx=Math.floor(x*2);add(x,.32,root+24+scales[scale][(motif[idx]+(sec.name.includes("Final")&&idx%3===0?1:0))%7],.55+sec.energy*.28)}return ev}if(def.role==="fx"&&bar%8===7){for(let x=0;x<4;x+=.5)add(x,.2,72+Math.floor(x*2),.45+x*.08);return ev}if(def.role==="texture"){add(0,3.8,root+24,.28)}return ev}
function active(role:TrackRole,e:number,name:string){if(name==="Intro")return["drums","chords","pad","texture"].includes(role);if(name==="Outro")return!["lead","countermelody"].includes(role);if(name.includes("Final"))return true;if(name.includes("Chorus"))return e>.75||role!=="fx";if(name.includes("Bridge")||name.includes("Breakdown"))return["drums","bass","pad","hook","texture","fx"].includes(role);return["drums","percussion","bass","chords","melody","hook","texture"].includes(role)}
function renderMidi(song:GeneratedSong,tracks:GeneratedTrack[]){const midi=new Midi();midi.header.setTempo(song.bpm);tracks.forEach(t=>{const tr=midi.addTrack();tr.name=t.name;if(t.program!==null)tr.instrument.number=t.program;t.events.forEach(e=>tr.addNote({midi:e.note,time:e.time,duration:e.duration,velocity:e.velocity}))});return midi.toArray()}
export function dataUrl(base64:string,type:string){return`data:${type};base64,${base64}`}
function swingBeat(b:number,s:number){return b+(Math.round(b*4)%2===1?s/100*.12:0)}function human(r:()=>number,a:number){return(r()-.5)*a}function pick<T>(r:()=>number,a:T[]){return a[Math.floor(r()*a.length)]}function ri(r:()=>number,min:number,max:number){return Math.floor(r()*(max-min+1))+min}function clamp(n:number,min:number,max:number){return Math.max(min,Math.min(max,n))}function swingLevelFor(range:[number,number],r:()=>number):SwingLevel{const opts=(Object.keys(levels) as SwingLevel[]).filter(l=>levels[l][1]>=range[0]&&levels[l][0]<=range[1]);return pick(r,opts)}function safe(s:string){return s.replace(/[^a-z0-9]+/gi,"")}function hash(s:string){let h=1779033703^s.length;for(let i=0;i<s.length;i++){h=Math.imul(h^s.charCodeAt(i),3432918353);h=h<<13|h>>>19}return h>>>0}function mulberry(a:number){return()=>{let t=a+=0x6d2b79f5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}function bytesToBase64(bytes:Uint8Array){let bin="";bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin)}function base64ToBytes(b64:string){const bin=atob(b64);return Uint8Array.from(bin,c=>c.charCodeAt(0))}
